spring:
  #profiles:
  #  active: @spring.profiles.active@
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev_db
    username: postgres
    password: lock
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  profiles: student
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stud_db    # temp example
    username: postgres
    password: lock